# This config file allows you to configure defaults for the analog daddy tool
# and the dashboard.
# Unsupported options are marked as such and will not be applied.

# The following section can be used to configure the tool settings.
[tool]
method_key = "METHOD"
warning_key = "WARNING"
# The importer will output information about the imported data in real-time.
importer_verbose = true

######### BEGIN DASHBOARD CONFIGURATION #########
# The following section can be used to configure the dashboard settings.
[dashboard]
# The following settings can be changed at runtime.
# However, use this file to set the defaults.
# Options: "centered", "wide".
layout = "centered"
# Options: "expanded", "collapsed", "auto".
initial_sidebar_state="expanded"
# If set to true, the dashboard will run in debug mode by default.
debug_mode = false
######### END OF DASHBOARD CONFIGURATION #########

# The following section are used if the settings for the given technology cannot
# be found. Copy and modify this section to create a new technology configuration.
[example_technology_settings]
# The technology_info field will be used to write the 'info' field in the
# LUT. And while reading the LUT, it will be used to load the correct configuration
# corresponding to the LUT loaded.
technology_info = "GPDK 45nm spectre"
# Constants to avoid magic strings throughout the python code.
# As well as to make sure the code functions for all technologies.
parameter_tag = "Parameters:"
gm_key_start = "gm_"
length_key = "length"
gs_key = "gs"
ds_key = "ds"
sb_key = "sb"
db_key = "db"
gb_key = "gb"
# Supply Voltage (vdd) in Volts.
vdd = "1.2"
# for technologies that only allow stacking and multipliers.
# Is the length/width an integer?
is_integer = false
# Length Range (in m)
l_min = "45n"
l_max = "10u"
length_increment = "10n"
# Width Range (in m) (Per-Finger)
w_min = "90n"
w_max = "100u"
# Voltage Step Size = 20 mV. This is the default step size
# which will be selected for our voltage sweeps.
# Note that decreasing sizes would not lead to more accurate results
# since the lookup function interpolates.
voltage_step_size = "20m"

[freepdk_45nm]
technology_info = "freepdk 45nm ngspice"
parameter_tag = "Parameters:"
gm_key_start = "gm_"
length_key = "length"
gs_key = "gs"
ds_key = "ds"
sb_key = "sb"
db_key = "db"
gb_key = "gb"
# Max Supply Voltage (Vdd) in Volts
vdd = "1"
# FinFET technologies only allow stacking and multipliers.
is_integer = false
# Length Range (in m)
l_min = "45n"
l_max = "10u"
length_increment = "10n"
# Width Range (in m) (Per-Finger)
w_min = "90n"
w_max = "1m"
voltage_step_size = "20m"